sb = float(input('Qual era o salário bruto anual daquele funcionário?'))
t = float(input('Quantos porcentos (%) eram deduzidos de taxas?'))
sl = sb * ((100 - t)/100)
c = (15/100)
print ('O salário liquido do funcionário era de €{}?'.format(sl))
sab = sb+(sb*c)
sal = sl+(sl*c)
print ('E com a correção de {} quanto será o salário dele?'.format(c))
print ('o salário bruto anual dele dele será de €{} mas ele só vai levar pra casa o liqudio, no valor de €{}'.format(sab,sal))
