p = float(input('Olá, quanto custa essa bolsa?'))
desc = int(input('seria possível fazer um desconto? Se sim, qual seria o desconto?'))
pdesc = p * ((100 - desc)/100)
print('hmmm! com {}% de desconto, começa ficar interessante, qual é o preço do produto final?'.format(desc))
print(pdesc)
print ('Maravilha, pode embrulhar para presente')
print ('é para já')
print ('Muito obrigada :)')
print ('O prazer é nosso, volte sempre')